### PR TITLE
#2: improve storage

### PR DESCRIPTION
**Pull request by sermachage**

### CODE REVIEW

**Comment by sermachage** [comment]
@vyonnegichovi please review this PR & Merge

**Comment by yvonnegichovi** [comment]
The PR is ready for merging

**Comment by Ysamwel** [comment]
This seems wonderful.  Cant wait to see the end result. Continue improving

**Comment by sermachage** [comment]
@Ysamwel thank you.

**Review by sermachage — COMMENTED** [review]
LGTM

**Pull request merged**
